import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Button from "@/components/Button";
import { LuSearch } from "react-icons/lu";
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} `}>
        <div id="header-container">
          <header className="max-width py-6">
            <p>logo</p>
            Global Navigation
            <Button
              // label="hello"
              icon={<LuSearch />}
              // variant="hollow"
              /* className="rounded-l-none" */ /* variant="hollow" */
            />
          </header>
        </div>

        <div id="page-container" className="max-width min-h-screen py-8">
          {children}
        </div>

        <div id="footer-container" className="bg-grey-light py-8">
          <footer className="max-width ">
            <h1>Footer</h1>
          </footer>
        </div>
      </body>
    </html>
  );
}
