import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} `}>
        <nav className="max-width">Global Navigation</nav>

        <div id="page-container" className="max-width">
          {children}
        </div>

        <div id="footer-container" className="bg-grey-light py-8">
          <footer className="max-width ">
            <h1>Footer</h1>
          </footer>
        </div>
      </body>
    </html>
  );
}
